# Generated by Django 4.2 on 2023-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("budget", models.IntegerField(null=True)),
                ("homepage", models.CharField(blank=True, max_length=1000, null=True)),
                ("overview", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "popularity",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("release_date", models.DateField(null=True)),
                ("revenue", models.BigIntegerField(null=True)),
                ("runtime", models.IntegerField(null=True)),
                (
                    "movie_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tagline", models.CharField(blank=True, max_length=1000, null=True)),
                ("vote_average", models.DecimalField(decimal_places=2, max_digits=4)),
                ("vote_count", models.IntegerField(null=True)),
            ],
        ),
    ]
